services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=arka    # Se crea la base de datos arka
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data